/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Admin_Reset extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Reset
     */
    public Admin_Reset() {
        initComponents();
    }
      DBConnect dbc;
     int flag = 0;
     
      public boolean checkpass(String str) {
        int upper = 0, lower = 0, number = 0, special = 0;

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                upper++;
            } else if (ch >= 'a' && ch <= 'z') {
                lower++;
            } else if (ch >= '0' && ch <= '9') {
                number++;
            } else {
                special++;
            }
        }
        if (upper >= 1 && lower >= 1 && number >= 1 && special == 0) {
            return true;
        } else {
            return false;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adclr = new javax.swing.JButton();
        adver = new javax.swing.JButton();
        adback = new javax.swing.JButton();
        adup = new javax.swing.JButton();
        adnewpa = new javax.swing.JPasswordField();
        adnpl = new javax.swing.JLabel();
        admbr = new javax.swing.JTextField();
        adnidr = new javax.swing.JTextField();
        adcon = new javax.swing.JTextField();
        adnplab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verification");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your Mobile and NID number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile NO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NID No :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        adclr.setBackground(new java.awt.Color(255, 204, 204));
        adclr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adclr.setText("Clear");
        adclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adclrActionPerformed(evt);
            }
        });
        getContentPane().add(adclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, -1));

        adver.setBackground(new java.awt.Color(204, 255, 204));
        adver.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adver.setText("Verify");
        adver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adverActionPerformed(evt);
            }
        });
        getContentPane().add(adver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 110, -1));

        adback.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        adback.setForeground(new java.awt.Color(255, 0, 0));
        adback.setText("<<<");
        adback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbackActionPerformed(evt);
            }
        });
        getContentPane().add(adback, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 447, 90, 30));

        adup.setBackground(new java.awt.Color(0, 255, 204));
        adup.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adup.setText("Update");
        adup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adupActionPerformed(evt);
            }
        });
        getContentPane().add(adup, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 110, 30));

        adnewpa.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adnewpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adnewpaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adnewpaMouseExited(evt);
            }
        });
        getContentPane().add(adnewpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 180, 30));

        adnpl.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adnpl.setForeground(new java.awt.Color(255, 255, 255));
        adnpl.setText("New Password :");
        getContentPane().add(adnpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 40));

        admbr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        admbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admbrActionPerformed(evt);
            }
        });
        getContentPane().add(admbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 240, 40));

        adnidr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(adnidr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 240, 40));

        adcon.setEditable(false);
        adcon.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        adcon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adconActionPerformed(evt);
            }
        });
        getContentPane().add(adcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 360, 50));

        adnplab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adnplab.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(adnplab, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 350, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adclrActionPerformed
        admbr.setText("");
        adnidr.setText("");

        adcon.setText("");
        adnewpa.setText("");
        adcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_adclrActionPerformed

    private void adverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adverActionPerformed

        String admobile = admbr.getText();
        String adnid = adnidr.getText();

        if (admobile.equals("") || adnid.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        }

     try {
              dbc = new DBConnect();
              dbc.connectToDB();
             
                 String sql = "SELECT * FROM ADMINREG WHERE NID='" + adnid+ "' AND MOBILE='" + admobile+ "' ";
                 
                 ResultSet rs;
                rs = dbc.queryToDB(sql);
               
                
                
            if (rs.next()) {
                adcon.setBackground(Color.GREEN);
                adcon.setText("  !!! Verification Successful !!!");
                flag = 1;

            } else {

                adcon.setBackground(Color.RED);
                adcon.setText(" Sorry  !!! Profile Not Found  !!!");

            }
          dbc.disconnectFromDB();  

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_adverActionPerformed

    private void adbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbackActionPerformed
        AdminLog adlog = new AdminLog();
        adlog.setVisible(true);
        dispose();
    }//GEN-LAST:event_adbackActionPerformed

    private void adupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adupActionPerformed
        if (flag == 1) {
            String newp = new String(adnewpa.getPassword());
            String admobile = admbr.getText();
            String adnid = adnidr.getText();

            boolean adrpa = checkpass(newp);
             dbc = new DBConnect();
                 try {
                if (newp.length() == 8 && (adrpa)) {
                dbc.connectToDB();
                String sql = " UPDATE ADMINREG SET PASS='" + newp + "'   WHERE NID='" + adnid + "' AND MOBILE='" + admobile + "' ";
                dbc.insertDataToDB(sql);
             
                   
                    JOptionPane.showMessageDialog(null, " Successfully Update the password", "Hurrah!!", JOptionPane.DEFAULT_OPTION);

                       dbc.disconnectFromDB();
                       dispose();

                    AdminLog a=new AdminLog();
                    a.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Password ", "Warning", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
            adcon.setBackground(Color.YELLOW);
            adcon.setText("Please Verify Yourself");
        }
    }//GEN-LAST:event_adupActionPerformed

    private void adnewpaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adnewpaMouseEntered
        adnplab.setText("*Must be 8 characters (At least 1 Capital Letter & 1 Number)");
    }//GEN-LAST:event_adnewpaMouseEntered

    private void adnewpaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adnewpaMouseExited
        adnplab.setText("");
    }//GEN-LAST:event_adnewpaMouseExited

    private void admbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admbrActionPerformed

    private void adconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adback;
    private javax.swing.JButton adclr;
    private javax.swing.JTextField adcon;
    private javax.swing.JTextField admbr;
    private javax.swing.JPasswordField adnewpa;
    private javax.swing.JTextField adnidr;
    private javax.swing.JLabel adnpl;
    private javax.swing.JLabel adnplab;
    private javax.swing.JButton adup;
    private javax.swing.JButton adver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
