/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author safwa
 */
public class AdminLog extends javax.swing.JFrame {

    /**
     * Creates new form AdminLog
     */
    public AdminLog() {
        initComponents();
    }
    DBConnect dbc;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back_btn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admail = new javax.swing.JTextField();
        adpass = new javax.swing.JPasswordField();
        adlog_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adlog_resbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 414, 79));

        back_btn2.setBackground(new java.awt.Color(0, 0, 0));
        back_btn2.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        back_btn2.setForeground(new java.awt.Color(255, 0, 0));
        back_btn2.setText("<<<");
        back_btn2.setPreferredSize(new java.awt.Dimension(70, 50));
        back_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_btn2MouseExited(evt);
            }
        });
        back_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 40));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 216, 176, 34));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email      :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 164, 176, 41));

        admail.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(admail, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 164, 253, 41));

        adpass.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(adpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 216, 253, 40));

        adlog_btn.setBackground(new java.awt.Color(204, 255, 204));
        adlog_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        adlog_btn.setText("Login");
        adlog_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adlog_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adlog_btnMouseExited(evt);
            }
        });
        adlog_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adlog_btnActionPerformed(evt);
            }
        });
        getContentPane().add(adlog_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 280, 253, 51));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Forgotten Password?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 253, -1));

        adlog_resbtn.setBackground(new java.awt.Color(255, 153, 153));
        adlog_resbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        adlog_resbtn.setText("Reset");
        adlog_resbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adlog_resbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adlog_resbtnMouseExited(evt);
            }
        });
        adlog_resbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adlog_resbtnActionPerformed(evt);
            }
        });
        getContentPane().add(adlog_resbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btn2MouseEntered
        back_btn2.setForeground(Color.WHITE);
    }//GEN-LAST:event_back_btn2MouseEntered

    private void back_btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btn2MouseExited
        back_btn2.setForeground(Color.red);
    }//GEN-LAST:event_back_btn2MouseExited

    private void back_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn2ActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btn2ActionPerformed

    private void adlog_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlog_btnMouseEntered
        adlog_btn.setBackground(Color.GREEN);
    }//GEN-LAST:event_adlog_btnMouseEntered

    private void adlog_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlog_btnMouseExited
        adlog_btn.setBackground(new Color(179, 255, 179));
    }//GEN-LAST:event_adlog_btnMouseExited

    private void adlog_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adlog_btnActionPerformed
        String aduser = admail.getText();
        String adpa = new String(adpass.getPassword());
        if (aduser.equals("") || adpa.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                dbc = new DBConnect();
                dbc.connectToDB();

                String sql = "SELECT * FROM ADMINREG WHERE EMAIL='" + aduser + "' AND PASS='" + adpa + "'";

                ResultSet rs;
                rs = dbc.queryToDB(sql);
                if (rs.next()) {

                    Admin_Info ai = new Admin_Info();
                    ai.setOwn_id(Integer.parseInt(rs.getString(1)));

                    ai.setFname(rs.getString(2));
                    ai.setAg(Integer.parseInt(rs.getString(3)));
                    ai.setGen(rs.getString(4));
                    ai.setHt(rs.getString(5));
                    ai.setWt(rs.getString(6));
                    ai.setBl(rs.getString(7));
                    ai.setMob(rs.getString(8));
                    ai.setMail(rs.getString(9));
                    ai.setNd(rs.getString(10));
                    ai.setPa(rs.getString(11));
                    ai.setPic(rs.getString(12));
                    ai.setPin(rs.getString(13));

                    dispose();
                    AdminMain am = new AdminMain(ai);
                    am.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Password or Email", "Warning", JOptionPane.ERROR_MESSAGE);
                    admail.setText("");
                    adpass.setText("");
                }
                dbc.disconnectFromDB();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_adlog_btnActionPerformed

    private void adlog_resbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlog_resbtnMouseEntered
        adlog_resbtn.setBackground(Color.red);
    }//GEN-LAST:event_adlog_resbtnMouseEntered

    private void adlog_resbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlog_resbtnMouseExited
        adlog_resbtn.setBackground(new Color(255, 128, 128));
    }//GEN-LAST:event_adlog_resbtnMouseExited

    private void adlog_resbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adlog_resbtnActionPerformed
        Admin_Reset adr = new Admin_Reset();
        adr.setVisible(true);
        dispose();
    }//GEN-LAST:event_adlog_resbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adlog_btn;
    private javax.swing.JButton adlog_resbtn;
    private javax.swing.JTextField admail;
    private javax.swing.JPasswordField adpass;
    private javax.swing.JButton back_btn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
