/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Member_Reset extends javax.swing.JFrame {

    /**
     * Creates new form Member_Reset
     */
    public Member_Reset() {
        initComponents();
    }
    DBConnect dbc;
     int flag = 0;
     
      public boolean checkpass(String str) {
        int upper = 0, lower = 0, number = 0, special = 0;

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                upper++;
            } else if (ch >= 'a' && ch <= 'z') {
                lower++;
            } else if (ch >= '0' && ch <= '9') {
                number++;
            } else {
                special++;
            }
        }
        if (upper >= 1 && lower >= 1 && number >= 1 && special == 0) {
            return true;
        } else {
            return false;

        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mclr = new javax.swing.JButton();
        mver = new javax.swing.JButton();
        mmbr = new javax.swing.JTextField();
        mnidr = new javax.swing.JTextField();
        mcon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mnewpa = new javax.swing.JPasswordField();
        mup = new javax.swing.JButton();
        mback = new javax.swing.JButton();
        mrplab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 700, 500));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verification");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 50));

        jLabel2.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your Mobile and NID number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile NO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NID No :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        mclr.setBackground(new java.awt.Color(255, 204, 204));
        mclr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mclr.setText("Clear");
        mclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mclrActionPerformed(evt);
            }
        });
        getContentPane().add(mclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, -1));

        mver.setBackground(new java.awt.Color(204, 255, 204));
        mver.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mver.setText("Verify");
        mver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mverActionPerformed(evt);
            }
        });
        getContentPane().add(mver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 110, -1));

        mmbr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mmbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmbrActionPerformed(evt);
            }
        });
        getContentPane().add(mmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 240, 40));

        mnidr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mnidr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidrActionPerformed(evt);
            }
        });
        getContentPane().add(mnidr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 240, 40));

        mcon.setEditable(false);
        mcon.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mconActionPerformed(evt);
            }
        });
        getContentPane().add(mcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 360, 50));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 40));

        mnewpa.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mnewpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnewpaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnewpaMouseExited(evt);
            }
        });
        getContentPane().add(mnewpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 180, 30));

        mup.setBackground(new java.awt.Color(0, 255, 204));
        mup.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mup.setText("Update");
        mup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mupActionPerformed(evt);
            }
        });
        getContentPane().add(mup, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 110, 30));

        mback.setBackground(new java.awt.Color(0, 0, 0));
        mback.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        mback.setForeground(new java.awt.Color(255, 0, 0));
        mback.setText("<<<");
        mback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbackActionPerformed(evt);
            }
        });
        getContentPane().add(mback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 90, 30));

        mrplab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mrplab.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(mrplab, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 360, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mclrActionPerformed
        mmbr.setText("");
        mnidr.setText("");

        mcon.setText("");
        mnewpa.setText("");
        mcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_mclrActionPerformed

    private void mverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mverActionPerformed
        String admobile = mmbr.getText();
        String adnid = mnidr.getText();

        if (admobile.equals("") || adnid.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        }

        try {
              dbc = new DBConnect();
              dbc.connectToDB();
             
                 String sql = "SELECT * FROM MEMBEREG WHERE NID='" + adnid+ "' AND MOBILE='" + admobile+ "' ";
                 
                 ResultSet rs;
                rs = dbc.queryToDB(sql);
               
                
                
            if (rs.next()) {
                mcon.setBackground(Color.GREEN);
                mcon.setText("  !!! Verification Successful !!!");
                flag = 1;

            } else {

                mcon.setBackground(Color.RED);
                mcon.setText(" Sorry  !!! Profile Not Found  !!!");

            }
          dbc.disconnectFromDB();  

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mverActionPerformed

    private void mmbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmbrActionPerformed

    }//GEN-LAST:event_mmbrActionPerformed

    private void mnidrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidrActionPerformed

    }//GEN-LAST:event_mnidrActionPerformed

    private void mconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mconActionPerformed

    }//GEN-LAST:event_mconActionPerformed

    private void mnewpaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnewpaMouseEntered
        mrplab.setText("*Must be 8 characters (At least 1 Capital Letter & 1 Number)");
    }//GEN-LAST:event_mnewpaMouseEntered

    private void mnewpaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnewpaMouseExited
        mrplab.setText("");
    }//GEN-LAST:event_mnewpaMouseExited

    private void mupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mupActionPerformed
        if (flag == 1) {
            String mnewp = new String(mnewpa.getPassword());
            String mmobile = mmbr.getText();
            String mnid = mnidr.getText();

            boolean madrpa = checkpass(mnewp);
               dbc = new DBConnect();
            try {
                if (mnewp.length() == 8 && (madrpa)) {
                dbc.connectToDB();
                String sql = " UPDATE MEMBEREG SET PASS='" + mnewp + "'   WHERE NID='" + mnid + "' AND MOBILE='" + mmobile + "' ";
                dbc.insertDataToDB(sql);
             
                   
                    JOptionPane.showMessageDialog(null, " Successfully Update the password", "Hurrah!!", JOptionPane.DEFAULT_OPTION);

                       dbc.disconnectFromDB();
                       dispose();

                    MemberLog m=new MemberLog();
                    m.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Password ", "Warning", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
            mcon.setBackground(Color.YELLOW);
            mcon.setText("Please Verify Yourself");
        }
    }//GEN-LAST:event_mupActionPerformed

    private void mbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbackActionPerformed
        MemberLog m = new MemberLog();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_mbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member_Reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton mback;
    private javax.swing.JButton mclr;
    private javax.swing.JTextField mcon;
    private javax.swing.JTextField mmbr;
    private javax.swing.JPasswordField mnewpa;
    private javax.swing.JTextField mnidr;
    private javax.swing.JLabel mrplab;
    private javax.swing.JButton mup;
    private javax.swing.JButton mver;
    // End of variables declaration//GEN-END:variables
}
