/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author safwa
 */
public class MemberLog extends javax.swing.JFrame {

    /**
     * Creates new form MemberLog
     */
    public MemberLog() {
        initComponents();
    }
    DBConnect dbc;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        res = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Mmeber_logbtn = new javax.swing.JButton();
        mpass = new javax.swing.JPasswordField();
        memail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 700, 500));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 53, 222, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email      :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 170, -1, 38));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 235, -1, -1));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("<<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 40));

        res.setBackground(new java.awt.Color(255, 204, 204));
        res.setText("Reset");
        res.setToolTipText("");
        res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resMouseExited(evt);
            }
        });
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Forgotten Password?");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        Mmeber_logbtn.setBackground(new java.awt.Color(204, 255, 204));
        Mmeber_logbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Mmeber_logbtn.setText("Login");
        Mmeber_logbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mmeber_logbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mmeber_logbtnMouseExited(evt);
            }
        });
        Mmeber_logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mmeber_logbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Mmeber_logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 220, 50));

        mpass.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpassActionPerformed(evt);
            }
        });
        getContentPane().add(mpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 230, 40));

        memail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        memail.setToolTipText("");
        getContentPane().add(memail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setForeground(Color.WHITE);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setForeground(Color.red);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void resMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resMouseEntered
        res.setBackground(Color.red);
    }//GEN-LAST:event_resMouseEntered

    private void resMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resMouseExited
        res.setBackground(new Color(255, 128, 128));
    }//GEN-LAST:event_resMouseExited

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        Member_Reset mdr = new Member_Reset();
        mdr.setVisible(true);
        dispose();
    }//GEN-LAST:event_resActionPerformed

    private void Mmeber_logbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mmeber_logbtnMouseEntered
        Mmeber_logbtn.setBackground(Color.GREEN);
    }//GEN-LAST:event_Mmeber_logbtnMouseEntered

    private void Mmeber_logbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mmeber_logbtnMouseExited
        Mmeber_logbtn.setBackground(new Color(179, 255, 179));
    }//GEN-LAST:event_Mmeber_logbtnMouseExited

    private void Mmeber_logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mmeber_logbtnActionPerformed
        String mail = memail.getText();
        String mpa = new String(mpass.getPassword());
        if (mail.equals("") || mpa.equals("")) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        } else {

            try {

                dbc = new DBConnect();
                dbc.connectToDB();

                String sql = "SELECT * FROM MEMBEREG WHERE EMAIL='" + mail + "' AND PASS='" + mpa + "'";

                ResultSet rs;
                rs = dbc.queryToDB(sql);
                if (rs.next()) {
                    Member_Info mem_info = new Member_Info();
                    mem_info.setOwn_id(Integer.parseInt(rs.getString(1)));

                    mem_info.setFname(rs.getString(2));
                    mem_info.setAg(Integer.parseInt(rs.getString(3)));
                    mem_info.setGen(rs.getString(4));
                    mem_info.setHt(rs.getString(5));
                    mem_info.setWt(rs.getString(6));
                    mem_info.setBl(rs.getString(7));
                    mem_info.setMob(rs.getString(8));
                    mem_info.setMail(rs.getString(9));
                    mem_info.setNd(rs.getString(10));
                    mem_info.setPa(rs.getString(11));
                    mem_info.setPic(rs.getString(12));

                    mem_info.setT_name(rs.getString(13));
                    mem_info.setT_id(Integer.parseInt(rs.getString(14)));
                    mem_info.setBill(Integer.parseInt(rs.getString(15)));
                    mem_info.setPack(rs.getString(16));
                    mem_info.setAod(rs.getString(17));

                    dispose();
                    MemberMain mem = new MemberMain(mem_info);
                    mem.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, " Invalid Password or Email", "Warning", JOptionPane.ERROR_MESSAGE);
                    memail.setText("");
                    mpass.setText("");
                }
                dbc.disconnectFromDB();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_Mmeber_logbtnActionPerformed

    private void mpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mmeber_logbtn;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField memail;
    private javax.swing.JPasswordField mpass;
    private javax.swing.JButton res;
    // End of variables declaration//GEN-END:variables
}
