/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author safwa
 */
public class MemberMain extends javax.swing.JFrame {

    /**
     * Creates new form MemberMain
     */
    Member_Info mem_info;
    DBConnect dbc;
    int flag = 0;
    String path = null;
    String id_equip = null;
    String my = null;

    public MemberMain(Member_Info mem_info) {
        initComponents();
        this.mem_info = mem_info;

        g_id.setText(Integer.toString(mem_info.getOwn_id()));
        f_name.setText(mem_info.getFname());
        age.setText(Integer.toString(mem_info.getAg()));
        gender.setText(mem_info.getGen());
        height.setText(mem_info.getHt());
        weight.setText(mem_info.getWt());
        bg.setText(mem_info.getBl());
        mobile.setText(mem_info.getMob());
        email.setText(mem_info.getMail());
        nid.setText(mem_info.getNd());
        String img = mem_info.getPic();
        ImageIcon newimage = new ImageIcon(img);
        pic.setIcon(newimage);

        trainer.setText(mem_info.getT_name());
        bill.setText(Integer.toString(mem_info.getBill()));
        pack.setText(mem_info.getPack());
        date.setText(mem_info.getAod());

        mem_pic_choser.setVisible(false);
        pic_path.setVisible(false);
        mem_apply.setVisible(false);
        mem_clr.setVisible(false);

        b_bill.setText(Integer.toString(mem_info.getBill()));
        b_pack.setText(mem_info.getPack());

        path = img;

        apply_equip.setVisible(false);
        Cancel_equip.setVisible(false);
        p.setForeground(Color.WHITE);
        prb.setEditable(false);

        mem_b_app.setVisible(false);
        mem_b_can.setVisible(false);

    }

    public boolean checkmobile(String str) {
        int upper = 0, lower = 0, number = 0, special = 0;

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                upper++;
            } else if (ch >= 'a' && ch <= 'z') {
                lower++;
            } else if (ch >= '0' && ch <= '9') {
                number++;
            } else {
                special++;
            }
        }
        if (special == 0 && upper == 0 && number == 11 && lower == 0) {
            return true;
        } else {
            return false;

        }
    }

    public boolean checkemail(String str) {
        int upper = 0, lower = 0, number = 0, special1 = 0, special2 = 0;

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                upper++;
            }
            if (ch >= 'a' && ch <= 'z') {
                lower++;
            }
            if (ch >= '0' && ch <= '9') {
                number++;
            }
            if (ch == '@') {
                special1++;
            }
            if (ch == '.') {
                special2++;
            }
        }
        if (special1 == 1 && special2 == 1 && upper == 0 && number >= 1 && lower >= 1) {
            return true;
        } else {
            return false;

        }
    }

    ResultSet resultset;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        ag = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        bg = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        w = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        pic = new javax.swing.JLabel();
        log_out_mem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        g_id = new javax.swing.JTextField();
        show_paa = new javax.swing.JLabel();
        trainer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bill = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pack = new javax.swing.JTextField();
        mem_pic_choser = new javax.swing.JButton();
        Mem_up = new javax.swing.JButton();
        mem_apply = new javax.swing.JButton();
        pic_path = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        mem_clr = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        equip_table = new javax.swing.JTable();
        p = new javax.swing.JLabel();
        show_equip = new javax.swing.JButton();
        prb = new javax.swing.JTextField();
        update_equip = new javax.swing.JButton();
        apply_equip = new javax.swing.JButton();
        Cancel_equip = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        log_out_mem1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        member_bill_table = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        b_pack = new javax.swing.JTextField();
        b_bill = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        bill_show = new javax.swing.JButton();
        mem_b_app = new javax.swing.JButton();
        mem_b_pay = new javax.swing.JButton();
        mem_b_can = new javax.swing.JButton();
        b_month = new com.toedter.calendar.JMonthChooser();
        b_year = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        select_bill_month = new javax.swing.JButton();
        b_b_mon_y = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        log_out_mem2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        search_by_week = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        mem_rou = new javax.swing.JTable();
        weekly = new javax.swing.JComboBox<>();
        week_day = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        log_out_mem3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, -1, 600));

        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Name");
        jLabel30.setToolTipText("");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        ag.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ag.setForeground(new java.awt.Color(255, 255, 255));
        ag.setText("Age");
        jPanel1.add(ag, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Height(cm)");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Blood Group");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        e.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        e.setForeground(new java.awt.Color(255, 255, 255));
        e.setText("Email");
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        email.setEditable(false);
        email.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 200, 40));

        bg.setEditable(false);
        bg.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bg.setToolTipText("");
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgMouseExited(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, 40));

        height.setEditable(false);
        height.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        height.setToolTipText("");
        jPanel1.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 40));

        age.setEditable(false);
        age.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 200, 40));

        f_name.setEditable(false);
        f_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel1.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 200, 40));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText(" Gender (M/F)");
        jLabel36.setToolTipText("");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        w.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        w.setForeground(new java.awt.Color(255, 255, 255));
        w.setText("Weight(kg)");
        w.setToolTipText("");
        jPanel1.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        m.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Mobile");
        m.setToolTipText("");
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("NID");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        nid.setEditable(false);
        nid.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nidMouseExited(evt);
            }
        });
        jPanel1.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 200, 40));

        mobile.setEditable(false);
        mobile.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mobileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobileMouseExited(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 200, 40));

        weight.setEditable(false);
        weight.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 200, 40));

        gender.setEditable(false);
        gender.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 200, 40));

        pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 260, 240));

        log_out_mem.setBackground(new java.awt.Color(0, 0, 0));
        log_out_mem.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log_out_mem.setForeground(new java.awt.Color(255, 255, 204));
        log_out_mem.setText("Log Out");
        log_out_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_memActionPerformed(evt);
            }
        });
        jPanel1.add(log_out_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 80, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gym ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        g_id.setEditable(false);
        g_id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel1.add(g_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 200, 40));

        show_paa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        show_paa.setForeground(new java.awt.Color(255, 0, 51));
        show_paa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(show_paa, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 230, 60));

        trainer.setEditable(false);
        trainer.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerActionPerformed(evt);
            }
        });
        jPanel1.add(trainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 200, 40));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trainer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bill");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        bill.setEditable(false);
        bill.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel1.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 200, 40));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Package");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        pack.setEditable(false);
        pack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packActionPerformed(evt);
            }
        });
        jPanel1.add(pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 200, 40));

        mem_pic_choser.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        mem_pic_choser.setText("Attach");
        mem_pic_choser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_pic_choserActionPerformed(evt);
            }
        });
        jPanel1.add(mem_pic_choser, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 90, 30));

        Mem_up.setBackground(new java.awt.Color(255, 204, 153));
        Mem_up.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        Mem_up.setText("Update");
        Mem_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mem_upActionPerformed(evt);
            }
        });
        jPanel1.add(Mem_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 110, 30));

        mem_apply.setBackground(new java.awt.Color(153, 255, 153));
        mem_apply.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        mem_apply.setText("Apply");
        mem_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_applyActionPerformed(evt);
            }
        });
        jPanel1.add(mem_apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, 30));

        pic_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic_pathActionPerformed(evt);
            }
        });
        jPanel1.add(pic_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 260, 30));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Admission Date");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 200, 40));

        mem_clr.setBackground(new java.awt.Color(255, 0, 0));
        mem_clr.setFont(new java.awt.Font("Niagara Engraved", 1, 14)); // NOI18N
        mem_clr.setText("Cancel");
        mem_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_clrActionPerformed(evt);
            }
        });
        jPanel1.add(mem_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 80, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/table.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Profile", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equip_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipment ID", "Equipment Name", "Problem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equip_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equip_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(equip_table);
        if (equip_table.getColumnModel().getColumnCount() > 0) {
            equip_table.getColumnModel().getColumn(0).setResizable(false);
            equip_table.getColumnModel().getColumn(0).setPreferredWidth(40);
            equip_table.getColumnModel().getColumn(1).setResizable(false);
            equip_table.getColumnModel().getColumn(2).setResizable(false);
            equip_table.getColumnModel().getColumn(2).setPreferredWidth(120);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 600, 230));

        p.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("Problem");
        jPanel4.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 110, 30));

        show_equip.setBackground(new java.awt.Color(0, 0, 0));
        show_equip.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        show_equip.setForeground(new java.awt.Color(0, 0, 255));
        show_equip.setText("Show");
        show_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_equipActionPerformed(evt);
            }
        });
        jPanel4.add(show_equip, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 120, 40));

        prb.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel4.add(prb, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 310, 50));

        update_equip.setBackground(new java.awt.Color(255, 153, 51));
        update_equip.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        update_equip.setText("Update");
        update_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_equipActionPerformed(evt);
            }
        });
        jPanel4.add(update_equip, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 100, 40));

        apply_equip.setBackground(new java.awt.Color(0, 153, 0));
        apply_equip.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        apply_equip.setText("Apply");
        apply_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_equipActionPerformed(evt);
            }
        });
        jPanel4.add(apply_equip, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 100, 40));

        Cancel_equip.setBackground(new java.awt.Color(255, 0, 0));
        Cancel_equip.setFont(new java.awt.Font("Niagara Solid", 1, 18)); // NOI18N
        Cancel_equip.setText("Cancel");
        Cancel_equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_equipActionPerformed(evt);
            }
        });
        jPanel4.add(Cancel_equip, new org.netbeans.lib.awtextra.AbsoluteConstraints(963, 260, 100, 40));

        jLabel23.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Equipment Info");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 430, 50));

        log_out_mem1.setBackground(new java.awt.Color(0, 0, 0));
        log_out_mem1.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log_out_mem1.setForeground(new java.awt.Color(255, 255, 204));
        log_out_mem1.setText("Log Out");
        log_out_mem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_mem1ActionPerformed(evt);
            }
        });
        jPanel4.add(log_out_mem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 80, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/table.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Equipment", jPanel4);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        member_bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Billing Month", "Billing Amount", "Billing Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(member_bill_table);
        if (member_bill_table.getColumnModel().getColumnCount() > 0) {
            member_bill_table.getColumnModel().getColumn(0).setResizable(false);
            member_bill_table.getColumnModel().getColumn(1).setResizable(false);
            member_bill_table.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 510, 190));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Package");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        b_pack.setEditable(false);
        b_pack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jPanel2.add(b_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, 30));

        b_bill.setEditable(false);
        b_bill.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        b_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_billActionPerformed(evt);
            }
        });
        jPanel2.add(b_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, 30));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Bill Amount");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, 30));

        bill_show.setBackground(new java.awt.Color(51, 51, 255));
        bill_show.setFont(new java.awt.Font("Niagara Engraved", 0, 24)); // NOI18N
        bill_show.setText("Show");
        bill_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_showActionPerformed(evt);
            }
        });
        jPanel2.add(bill_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 110, 30));

        mem_b_app.setBackground(new java.awt.Color(51, 255, 51));
        mem_b_app.setFont(new java.awt.Font("Niagara Engraved", 0, 18)); // NOI18N
        mem_b_app.setText("Apply");
        mem_b_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_b_appActionPerformed(evt);
            }
        });
        jPanel2.add(mem_b_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 90, 40));

        mem_b_pay.setBackground(new java.awt.Color(255, 204, 153));
        mem_b_pay.setFont(new java.awt.Font("Niagara Engraved", 0, 18)); // NOI18N
        mem_b_pay.setText("Pay");
        mem_b_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_b_payActionPerformed(evt);
            }
        });
        jPanel2.add(mem_b_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 40));

        mem_b_can.setBackground(new java.awt.Color(255, 0, 51));
        mem_b_can.setFont(new java.awt.Font("Niagara Engraved", 0, 18)); // NOI18N
        mem_b_can.setText("Cancel");
        mem_b_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_b_canActionPerformed(evt);
            }
        });
        jPanel2.add(mem_b_can, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 90, 40));

        b_month.setMonth(0);
        jPanel2.add(b_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 30));
        jPanel2.add(b_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, 30));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Billing Month");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 30));

        select_bill_month.setFont(new java.awt.Font("Niagara Engraved", 0, 18)); // NOI18N
        select_bill_month.setText("Select");
        select_bill_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_bill_monthActionPerformed(evt);
            }
        });
        jPanel2.add(select_bill_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, 30));

        b_b_mon_y.setEditable(false);
        b_b_mon_y.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel2.add(b_b_mon_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 110, 30));

        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, java.awt.Color.white, null));
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 410, 260));

        jLabel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.white, null));
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 140));

        log_out_mem2.setBackground(new java.awt.Color(0, 0, 0));
        log_out_mem2.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log_out_mem2.setForeground(new java.awt.Color(255, 255, 204));
        log_out_mem2.setText("Log Out");
        log_out_mem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_mem2ActionPerformed(evt);
            }
        });
        jPanel2.add(log_out_mem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/table.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Bill", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Week");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 30));

        search_by_week.setBackground(new java.awt.Color(0, 0, 0));
        search_by_week.setFont(new java.awt.Font("Niagara Engraved", 0, 18)); // NOI18N
        search_by_week.setForeground(new java.awt.Color(255, 204, 204));
        search_by_week.setText("Search");
        search_by_week.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_weekActionPerformed(evt);
            }
        });
        jPanel5.add(search_by_week, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 90, 30));

        mem_rou.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Workout Name", "Sets", "Reps", "Date", "Week day", "Continue For"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(mem_rou);
        if (mem_rou.getColumnModel().getColumnCount() > 0) {
            mem_rou.getColumnModel().getColumn(0).setResizable(false);
            mem_rou.getColumnModel().getColumn(1).setResizable(false);
            mem_rou.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1060, 230));

        weekly.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", " " }));
        weekly.setSelectedIndex(7);
        weekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyActionPerformed(evt);
            }
        });
        jPanel5.add(weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 30));

        week_day.setFont(new java.awt.Font("Onyx", 1, 14)); // NOI18N
        week_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                week_dayActionPerformed(evt);
            }
        });
        jPanel5.add(week_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 130, 40));

        jLabel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, null, null));
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, 140));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Show Entire  Routine ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 150, 40));

        log_out_mem3.setBackground(new java.awt.Color(0, 0, 0));
        log_out_mem3.setFont(new java.awt.Font("Niagara Engraved", 1, 18)); // NOI18N
        log_out_mem3.setForeground(new java.awt.Color(255, 255, 204));
        log_out_mem3.setText("Log Out");
        log_out_mem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_mem3ActionPerformed(evt);
            }
        });
        jPanel5.add(log_out_mem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 80, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/table.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 470));

        jTabbedPane1.addTab("Routine", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 46, 1110, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/1200X700(backsteel).png"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mi = g_id.getText();
        try {
            dbc = new DBConnect();
            dbc.connectToDB();

            DefaultTableModel model = (DefaultTableModel) mem_rou.getModel();
            model.setRowCount(0);

            resultset = dbc.queryToDB("SELECT * FROM  ROUTINE WHERE MID=" + mi + " ");

            while (resultset.next()) {

                String wn = resultset.getString("WN");
                String set = String.valueOf(resultset.getInt("SE"));
                String rep = String.valueOf(resultset.getInt("REPS"));
                String ad = resultset.getString("AD");
                String we = resultset.getString("WEE");
                String con = String.valueOf(resultset.getInt("CON"));

                String tableData[] = {wn, set, rep, ad, we, con};
                DefaultTableModel tableModel = (DefaultTableModel) mem_rou.getModel();
                tableModel.addRow(tableData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void week_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_week_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_week_dayActionPerformed

    private void weeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyActionPerformed
        if (weekly.getSelectedIndex() == 0) {
            week_day.setText("Sunday");
        } else if (weekly.getSelectedIndex() == 1) {
            week_day.setText("Monday");
        } else if (weekly.getSelectedIndex() == 2) {
            week_day.setText("Tuesday");
        } else if (weekly.getSelectedIndex() == 3) {
            week_day.setText("Wednesday");
        } else if (weekly.getSelectedIndex() == 4) {
            week_day.setText("Thursday");
        } else if (weekly.getSelectedIndex() == 5) {
            week_day.setText("Friday");
        } else if (weekly.getSelectedIndex() == 6) {
            week_day.setText("Saturday");
        }
    }//GEN-LAST:event_weeklyActionPerformed

    private void search_by_weekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_weekActionPerformed
        String wee = week_day.getText();
        String mi = g_id.getText();
        if (wee.equals("") || mi.equals("")) {
            JOptionPane.showMessageDialog(null, "Caution", "Empty Week Day", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                dbc = new DBConnect();
                dbc.connectToDB();

                DefaultTableModel model = (DefaultTableModel) mem_rou.getModel();
                model.setRowCount(0);

                resultset = dbc.queryToDB("SELECT * FROM  ROUTINE WHERE MID=" + mi + " AND WEE='" + wee + "'  ");

                while (resultset.next()) {

                    String wn = resultset.getString("WN");
                    String set = String.valueOf(resultset.getInt("SE"));
                    String rep = String.valueOf(resultset.getInt("REPS"));
                    String ad = resultset.getString("AD");
                    String we = resultset.getString("WEE");
                    String con = String.valueOf(resultset.getInt("CON"));

                    String tableData[] = {wn, set, rep, ad, we, con};
                    DefaultTableModel tableModel = (DefaultTableModel) mem_rou.getModel();
                    tableModel.addRow(tableData);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_search_by_weekActionPerformed

    private void select_bill_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_bill_monthActionPerformed
        String mon = null;
        switch (b_month.getMonth()) {
            case 0:
                mon = "Jan";
                break;
            case 1:
                mon = "Feb";
                break;
            case 2:
                mon = "Mar";
                break;
            case 3:
                mon = "Apr";
                break;
            case 4:
                mon = "May";
                break;
            case 5:
                mon = "June";
                break;
            case 6:
                mon = "July";
                break;
            case 7:
                mon = "Aug";
                break;
            case 8:
                mon = "Sep";
                break;
            case 9:
                mon = "Oct";
                break;
            case 10:
                mon = "Nov";
                break;
            case 11:
                mon = "Dec";
                break;
            default:
                break;
        }

        int ye = b_year.getYear();
        String y = Integer.toString(ye);
        String halfy = y.length() > 2 ? y.substring(y.length() - 2) : y;

        String bill_month = mon + halfy;
        b_b_mon_y.setText(bill_month);
    }//GEN-LAST:event_select_bill_monthActionPerformed

    private void mem_b_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_b_canActionPerformed
        mem_b_app.setVisible(false);
        mem_b_can.setVisible(false);
        mem_b_pay.setVisible(true);
    }//GEN-LAST:event_mem_b_canActionPerformed

    private void mem_b_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_b_payActionPerformed
        my = b_b_mon_y.getText();

        if (my.equals("")) {

            JOptionPane.showMessageDialog(null, "Empty Billing Month", "Warning", JOptionPane.ERROR_MESSAGE);
            mem_b_app.setVisible(false);
            mem_b_can.setVisible(false);
        } else {
            if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING!!!",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                mem_b_app.setVisible(true);
                mem_b_can.setVisible(true);
                mem_b_pay.setVisible(false);
            }
        }

    }//GEN-LAST:event_mem_b_payActionPerformed

    private void mem_b_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_b_appActionPerformed
        int id = 1;
        String apin = null;
        try {

            dbc = new DBConnect();
            dbc.connectToDB();

            String sql = " SELECT PIN FROM ADMINREG WHERE AID=" + id + " ";

            ResultSet rs;
            rs = dbc.queryToDB(sql);
            if (rs.next()) {

                apin = rs.getString(1);

            }

            dbc.disconnectFromDB();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String pin = JOptionPane.showInputDialog("Please Enter The Current Pin for Verificaton ");
        if (pin.equals(apin)) {
            JOptionPane.showMessageDialog(null, "Verifired", "Correct Pin", JOptionPane.PLAIN_MESSAGE);

            int ba = Integer.parseInt(b_bill.getText());

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now = LocalDateTime.now();
            String bdate = dtf.format(now);

            int mid = Integer.parseInt(g_id.getText());

            dbc = new DBConnect();
            try {
                dbc.connectToDB();
                String sql = "INSERT INTO BILLS(MID,BM,BA,BD) VALUES(" + mid + ", '" + my + "'," + ba + ", '" + bdate + "')";
                boolean b = dbc.ADDToDB(sql);
                if (b) {
                    dbc.disconnectFromDB();

                    JOptionPane.showMessageDialog(null, " Payment Successful", "Hurrah!!", JOptionPane.DEFAULT_OPTION);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            try {
                dbc = new DBConnect();
                dbc.connectToDB();

                DefaultTableModel model = (DefaultTableModel) member_bill_table.getModel();
                model.setRowCount(0);

                resultset = dbc.queryToDB("SELECT BM,BA,BD FROM BILLS WHERE MID=" + mid + " ");

                while (resultset.next()) {
                    String bm = resultset.getString("BM");
                    String baa = String.valueOf(resultset.getInt("BA"));
                    String bd = resultset.getString("BD");

                    String tableData[] = {bm, baa, bd};
                    DefaultTableModel tableModel = (DefaultTableModel) member_bill_table.getModel();
                    tableModel.addRow(tableData);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            mem_b_app.setVisible(false);
            mem_b_can.setVisible(false);
            mem_b_pay.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Access Denied", "Wrong Pin", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_mem_b_appActionPerformed

    private void bill_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_showActionPerformed
        int mid = Integer.parseInt(g_id.getText());
        try {
            dbc = new DBConnect();
            dbc.connectToDB();

            DefaultTableModel model = (DefaultTableModel) member_bill_table.getModel();
            model.setRowCount(0);

            resultset = dbc.queryToDB("SELECT BM,BA,BD FROM BILLS WHERE MID=" + mid + " ORDER BY BD DESC ");

            while (resultset.next()) {
                String bm = resultset.getString("BM");
                String ba = String.valueOf(resultset.getInt("BA"));
                String bd = resultset.getString("BD");

                String tableData[] = {bm, ba, bd};
                DefaultTableModel tableModel = (DefaultTableModel) member_bill_table.getModel();
                tableModel.addRow(tableData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bill_showActionPerformed

    private void b_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_billActionPerformed

    private void Cancel_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_equipActionPerformed
        apply_equip.setVisible(false);
        Cancel_equip.setVisible(false);
        p.setForeground(Color.WHITE);
        prb.setEditable(false);
        update_equip.setVisible(true);
    }//GEN-LAST:event_Cancel_equipActionPerformed

    private void apply_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_equipActionPerformed

        String problem = prb.getText();
        int ida = Integer.parseInt(g_id.getText());

        dbc = new DBConnect();
        try {
            dbc.connectToDB();
            String sql = " UPDATE EQUIPMENT SET PROBLEM='" + problem + "' ,ENID=" + ida + " WHERE EID='" + id_equip + "' ";
            boolean b = dbc.insertDataToDB(sql);
            if (b) {
                JOptionPane.showMessageDialog(null, " Successfully Updated the Info", "Hurrah!!", JOptionPane.DEFAULT_OPTION);
                dbc.disconnectFromDB();

                p.setForeground(Color.WHITE);
                prb.setEditable(true);
                apply_equip.setVisible(false);
                Cancel_equip.setVisible(false);
                prb.setText("");
                update_equip.setVisible(true);

                try {
                    dbc = new DBConnect();
                    dbc.connectToDB();

                    DefaultTableModel model = (DefaultTableModel) equip_table.getModel();
                    model.setRowCount(0);

                    resultset = dbc.queryToDB("SELECT * FROM  EQUIPMENT ");

                    while (resultset.next()) {
                        String ide = resultset.getString("EID");
                        String namee = resultset.getString("ENAME");
                        String prb = resultset.getString("PROBLEM");

                        String tableData[] = {ide, namee, prb};
                        DefaultTableModel tableModel = (DefaultTableModel) equip_table.getModel();
                        tableModel.addRow(tableData);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_apply_equipActionPerformed

    private void update_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_equipActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING!!!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            String problem = prb.getText();
            if (problem.equals("")) {
                JOptionPane.showMessageDialog(null, "Opps!! Empty Field", "Warning", JOptionPane.ERROR_MESSAGE);
            } else {
                apply_equip.setVisible(true);
                Cancel_equip.setVisible(true);
                p.setForeground(Color.red);
                prb.setEditable(true);
                update_equip.setVisible(false);

            }

        }
    }//GEN-LAST:event_update_equipActionPerformed

    private void show_equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_equipActionPerformed
        try {
            dbc = new DBConnect();
            dbc.connectToDB();

            DefaultTableModel model = (DefaultTableModel) equip_table.getModel();
            model.setRowCount(0);

            resultset = dbc.queryToDB("SELECT * FROM  EQUIPMENT ");

            while (resultset.next()) {
                String id = resultset.getString("EID");
                String name = resultset.getString("ENAME");

                String prb = resultset.getString("PROBLEM");

                String tableData[] = {id, name, prb};
                DefaultTableModel tableModel = (DefaultTableModel) equip_table.getModel();
                tableModel.addRow(tableData);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_show_equipActionPerformed

    private void equip_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equip_tableMouseClicked
        int index = equip_table.getSelectedRow();
        TableModel model = equip_table.getModel();
        id_equip = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();
        String pr = model.getValueAt(index, 2).toString();

        prb.setText(pr);
    }//GEN-LAST:event_equip_tableMouseClicked

    private void mem_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_clrActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING!!!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            age.setEditable(false);
            weight.setEditable(false);
            email.setEditable(false);
            mobile.setEditable(false);

            ag.setForeground(Color.WHITE);
            w.setForeground(Color.WHITE);
            m.setForeground(Color.WHITE);
            e.setForeground(Color.WHITE);

            mem_pic_choser.setVisible(false);
            pic_path.setVisible(false);

            mem_apply.setVisible(false);
            mem_clr.setVisible(false);
            Mem_up.setVisible(true);

        } else {

        }
    }//GEN-LAST:event_mem_clrActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void pic_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pic_pathActionPerformed

    private void mem_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_applyActionPerformed
        String pin = JOptionPane.showInputDialog("Please Enter Your Password");
        String id = g_id.getText();
        try {
            dbc = new DBConnect();
            dbc.connectToDB();

            String sql = "SELECT * FROM MEMBEREG WHERE MID='" + id + "' AND PASS='" + pin + "' ";

            ResultSet rs;
            rs = dbc.queryToDB(sql);

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, " Thank you", "Verified!!", JOptionPane.DEFAULT_OPTION);
                flag = 1;

            } else {

                JOptionPane.showMessageDialog(null, "Opps!! Wrong Password", "Warning", JOptionPane.ERROR_MESSAGE);

            }
            dbc.disconnectFromDB();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if (flag == 1) {
            dbc = new DBConnect();
            try {
                String a = age.getText();
                String wt = weight.getText();
                String mob = mobile.getText();
                String mail = email.getText();
                String pic = pic_path.getText();

                boolean cm = checkmobile(mob);
                boolean ce = checkemail(mail);

                if (cm == true && ce == true) {

                    dbc.connectToDB();
                    String sql = " UPDATE MEMBEREG SET AGE='" + a + "' ,WE='" + wt + "' ,MOBILE='" + mob + "',EMAIL='" + mail + "',PIC='" + pic + "'  WHERE MID='" + id + "' AND PASS='" + pin + "' ";
                    dbc.insertDataToDB(sql);

                    JOptionPane.showMessageDialog(null, " Successfully Updated", "Hurrah!!", JOptionPane.DEFAULT_OPTION);

                    dbc.disconnectFromDB();

                    mem_pic_choser.setVisible(false);
                    pic_path.setVisible(false);
                    mem_apply.setVisible(false);
                    mem_clr.setVisible(false);
                    Mem_up.setVisible(true);

                    ag.setForeground(Color.WHITE);
                    w.setForeground(Color.WHITE);
                    m.setForeground(Color.WHITE);
                    e.setForeground(Color.WHITE);

                    age.setEditable(false);
                    weight.setEditable(false);
                    email.setEditable(false);
                    mobile.setEditable(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Opps!! Wrong Format", "Warning", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_mem_applyActionPerformed

    private void Mem_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mem_upActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING!!!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            age.setEditable(true);
            weight.setEditable(true);
            email.setEditable(true);
            mobile.setEditable(true);

            ag.setForeground(Color.red);
            w.setForeground(Color.red);
            m.setForeground(Color.red);
            e.setForeground(Color.red);

            mem_pic_choser.setVisible(true);
            pic_path.setVisible(true);
            pic_path.setText(path);
            mem_apply.setVisible(true);
            mem_clr.setVisible(true);
            Mem_up.setVisible(false);

        } else {

        }
    }//GEN-LAST:event_Mem_upActionPerformed

    private void mem_pic_choserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_pic_choserActionPerformed
        try {
            pic.setIcon(null);
            pic_path.setText("");
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            pic_path.setText(filename);
            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(filename);
            Image image = icon.getImage().getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH);
            pic.setIcon(icon);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mem_pic_choserActionPerformed

    private void packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void trainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainerActionPerformed

    private void log_out_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_memActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out_memActionPerformed

    private void mobileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileMouseExited

    }//GEN-LAST:event_mobileMouseExited

    private void mobileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileMouseEntered

    }//GEN-LAST:event_mobileMouseEntered

    private void nidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidMouseExited

    }//GEN-LAST:event_nidMouseExited

    private void nidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nidMouseEntered

    }//GEN-LAST:event_nidMouseEntered

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void bgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseExited

    }//GEN-LAST:event_bgMouseExited

    private void bgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseEntered

    }//GEN-LAST:event_bgMouseEntered

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited

    }//GEN-LAST:event_emailMouseExited

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered

    }//GEN-LAST:event_emailMouseEntered

    private void log_out_mem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_mem1ActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out_mem1ActionPerformed

    private void log_out_mem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_mem2ActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out_mem2ActionPerformed

    private void log_out_mem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_mem3ActionPerformed
        MemberLog mml = new MemberLog();
        mml.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out_mem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Member_Info mem_info = null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberMain(mem_info).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_equip;
    private javax.swing.JButton Mem_up;
    private javax.swing.JLabel ag;
    private javax.swing.JTextField age;
    private javax.swing.JButton apply_equip;
    private javax.swing.JTextField b_b_mon_y;
    private javax.swing.JTextField b_bill;
    private com.toedter.calendar.JMonthChooser b_month;
    private javax.swing.JTextField b_pack;
    private com.toedter.calendar.JYearChooser b_year;
    private javax.swing.JTextField bg;
    private javax.swing.JTextField bill;
    private javax.swing.JButton bill_show;
    private javax.swing.JTextField date;
    private javax.swing.JLabel e;
    private javax.swing.JTextField email;
    private javax.swing.JTable equip_table;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField g_id;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton log_out_mem;
    private javax.swing.JButton log_out_mem1;
    private javax.swing.JButton log_out_mem2;
    private javax.swing.JButton log_out_mem3;
    private javax.swing.JLabel m;
    private javax.swing.JButton mem_apply;
    private javax.swing.JButton mem_b_app;
    private javax.swing.JButton mem_b_can;
    private javax.swing.JButton mem_b_pay;
    private javax.swing.JButton mem_clr;
    private javax.swing.JButton mem_pic_choser;
    private javax.swing.JTable mem_rou;
    private javax.swing.JTable member_bill_table;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField nid;
    private javax.swing.JLabel p;
    private javax.swing.JTextField pack;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField pic_path;
    private javax.swing.JTextField prb;
    private javax.swing.JButton search_by_week;
    private javax.swing.JButton select_bill_month;
    private javax.swing.JButton show_equip;
    private javax.swing.JLabel show_paa;
    private javax.swing.JTextField trainer;
    private javax.swing.JButton update_equip;
    private javax.swing.JLabel w;
    private javax.swing.JTextField week_day;
    private javax.swing.JComboBox<String> weekly;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
