/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MN
 */
public class TrainerRegLog extends javax.swing.JFrame {

    /**
     * Creates new form TrainerRegLog
     */
    Info info;
    public TrainerRegLog(Info info) {
        initComponents();
        this.info=info;
        
    }
    int flag = 0;
    int flag2=0;
    
    DBConnect dbc;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_id = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tinfo = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        Trainer_reg_btn = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trainer Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 318, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose Trainer ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 179, 44));

        t_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1601", "1602", "1603", "1604", "1605", " " }));
        t_id.setSelectedIndex(5);
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        getContentPane().add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 118, 46));

        tinfo.setText("\n\n\n\n\n\n                           \n                     ***SELECT YOUR MENTOR *** ");
        jScrollPane1.setViewportView(tinfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 303, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Shift Time :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 179, 43));

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00 AM-10:00 AM", "10:00 AM-01:00 PM", "01:00 PM-04:00 PM", "04:00 PM-08:00 PM", "08:00 PM-11:00 PM", " " }));
        time.setSelectedIndex(5);
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 42));

        Trainer_reg_btn.setFont(new java.awt.Font("Niagara Engraved", 1, 24)); // NOI18N
        Trainer_reg_btn.setText("Register");
        Trainer_reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trainer_reg_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Trainer_reg_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 113, 42));

        date.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 160, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Joinning Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        if (t_id.getSelectedIndex() == 0) {
            flag = 1;
            tinfo.setText("\n\n\n\n\n              Mentor Name =Mr.Manik Azad  \n" + "              Trainer ID= 1601\n" + "               Package Name= Happy Member\n");
        } else if (t_id.getSelectedIndex() == 1) {
            flag = 2;
            tinfo.setText("\n\n\n\n\n              Mentor Name =Mr.Rabbi  \n" + "              Trainer ID= 1602\n" + "               Package Name=Super Saver\n");
        } else if (t_id.getSelectedIndex() == 2) {
            flag = 3;
            tinfo.setText("\n\n\n\n\n              Mentor Name =Mr. Asadul Islam Milon \n" + "              Trainer ID= 1603\n" + "               Package Name= Elite Member\n");
        } else if (t_id.getSelectedIndex() == 3) {
            flag = 4;
            tinfo.setText("\n\n\n\n\n              Mentor Name =Mr. Shahin  \n" + "              Trainer ID= 1604\n" + "               Package Name=Holiday Member\n");
        } else if (t_id.getSelectedIndex() == 4) {
            flag = 5;
            tinfo.setText("\n\n\n\n\n              Mentor Name =Ms. Nighat Sultana  \n" + "              Trainer ID= 1605\n" + "               Package Name= Female Member\n");
        } else //if(pack.getSelectedIndex() == 5)
        {
            flag = 0;
            tinfo.setText("\n\n\n\n\n                     ***SELECT YOUR MENTOR *** \n \n");
        }
    }//GEN-LAST:event_t_idActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        if (time.getSelectedIndex() == 0) {
            flag2 = 1;

        } else if (time.getSelectedIndex() == 1) {
            flag2 = 2;

        } else if (time.getSelectedIndex() == 2) {
            flag2 = 3;

        } else if (time.getSelectedIndex() == 3) {
            flag2 = 4;

        } else if (time.getSelectedIndex() == 4) {
            flag2 = 5;

        } else //if(pack.getSelectedIndex() == 5)
        {
            flag2 = 0;

        }
    }//GEN-LAST:event_timeActionPerformed

    private void Trainer_reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trainer_reg_btnActionPerformed
          
        String fname = info.getFname();
        //System.out.println(fname);
        int ag = info.getAg();
        //System.out.println(ag);
        String gen = info.getGen();
        String ht = info.getHt();
        String wt = info.getWt();
        String bl = info.getBl();
        String mob = info.getMob();
        String mail = info.getMail();
        String nd = info.getNd();
        String pa = info.getPa();
        String pic = info.getPic();

     

     
     String pac=null;
     String tr_name=null;
     String m_time=null;
     int tr_id=0;
     
     if (flag == 1) {
            pac = "Happy Member";
            tr_name = "Mr. Manik Azad";
            tr_id=1601;
            m_time=" 07:00 AM-10:00 AM";
        }  if (flag == 2) {
            pac = "Super Saver";
            tr_name = "Mr.Rabbi";
            tr_id=1602;
             m_time="10:00 AM-01:00 PM";
        }  if (flag == 3) {
            pac = "Elite Member";
            tr_name = "Mr. Asadul Islam Milon";
             tr_id=1603;
              m_time="01:00 PM-04:00 PM";
        }  if (flag == 4) {
            pac = "Holiday Member";
            tr_name = "Mr.Shahin ";
             tr_id=1604;
              m_time="04:00 PM-08:00 PM";
        }  if (flag == 5) {
            pac = "Female Member";
            tr_name = "Ms. Nighat Sultana";
             tr_id=1605;
              m_time="08:00 PM-11:00 PM";
        }
       
         String da=  (  (JTextField)date.getDateEditor().getUiComponent()).getText();
        
        
        String time=null;
        
         if (flag2 == 1) {
           time="07:00 AM-10:00 AM";
        }  if (flag2 == 2) {
          time="10:00 AM-01:00 PM";
        }  if (flag2 == 3) {
           time="01:00 PM-04:00 PM";
        }  if (flag2 == 4) {
            time="04:00 PM-08:00 PM";
        }  if (flag2 == 5) {
           time="08:00 PM-11:00 PM";
        }

        





      
    if(flag==0 || flag2==0 || da.equals("")){
        JOptionPane.showMessageDialog(null, "Opps!! Try Again", "Warning!! Empty Field", JOptionPane.ERROR_MESSAGE);
    }
    else{
      
        
        dbc = new DBConnect();
            try {
                
                dbc.connectToDB();

                dbc.insertDataToDB("INSERT INTO TRAINEREG(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,TNAME,M_TID,SHIFT,PAC,M_SHIFT,DOJ) VALUES('" + fname+ "', " + ag + ",'" + gen + "','" + ht + "','" + wt + "','" + bl + "','" + mob + "','" + mail + "','" + nd + "','" + pa + "','" + pic + "','" +tr_name  + "'," + tr_id + ",'" + time + "','" + pac + "','" + m_time + "','" + da + "')");
              
                 String sql = "SELECT TID FROM TRAINEREG WHERE NID='" + nd+ "' ";
                 String d=null;
                 ResultSet rs;
                rs = dbc.queryToDB(sql);
                while (rs.next()) {
                     d=rs.getString(1);
                    
                }
                
                dbc.disconnectFromDB();

                JOptionPane.showMessageDialog(null, " Your TRAINER ID is  "+d , "Registration Successful!!", JOptionPane.INFORMATION_MESSAGE);
                
                dispose();
                TrainerLog t = new TrainerLog();
                t.setVisible(true);
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
    }
    }//GEN-LAST:event_Trainer_reg_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerRegLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerRegLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerRegLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerRegLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        Info info=null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerRegLog(info).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Trainer_reg_btn;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> t_id;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JTextPane tinfo;
    // End of variables declaration//GEN-END:variables
}
