/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class Trainer_Reset extends javax.swing.JFrame {

    /**
     * Creates new form Trainer_Reset
     */
    public Trainer_Reset() {
        initComponents();
    }
    DBConnect dbc;
    int flag = 0;
    int count = 0;

    public boolean checkpass(String str) {
        int upper = 0, lower = 0, number = 0, special = 0;

        for (int i = 0; i < str.length(); i++) {
            char ch = str.charAt(i);
            if (ch >= 'A' && ch <= 'Z') {
                upper++;
            } else if (ch >= 'a' && ch <= 'z') {
                lower++;
            } else if (ch >= '0' && ch <= '9') {
                number++;
            } else {
                special++;
            }
        }
        if (upper >= 1 && lower >= 1 && number >= 1 && special == 0) {
            return true;
        } else {
            return false;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chose = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tmbr = new javax.swing.JTextField();
        tnidr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tclr = new javax.swing.JButton();
        tver = new javax.swing.JButton();
        tcon = new javax.swing.JTextField();
        tnewpa = new javax.swing.JPasswordField();
        tup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        trback = new javax.swing.JButton();
        trplab = new javax.swing.JLabel();
        mentor = new javax.swing.JRadioButton();
        FRESHER = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verification");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 50));

        jLabel2.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your Mobile and NID number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile NO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, 40));

        tmbr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tmbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbrActionPerformed(evt);
            }
        });
        getContentPane().add(tmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 240, 40));

        tnidr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(tnidr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 240, 40));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NID No :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        tclr.setBackground(new java.awt.Color(255, 204, 204));
        tclr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tclr.setText("Clear");
        tclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tclrActionPerformed(evt);
            }
        });
        getContentPane().add(tclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, -1));

        tver.setBackground(new java.awt.Color(204, 255, 204));
        tver.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tver.setText("Verify");
        tver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tverActionPerformed(evt);
            }
        });
        getContentPane().add(tver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 110, -1));

        tcon.setEditable(false);
        tcon.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tconActionPerformed(evt);
            }
        });
        getContentPane().add(tcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 360, 50));

        tnewpa.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tnewpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tnewpaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tnewpaMouseExited(evt);
            }
        });
        getContentPane().add(tnewpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 180, 30));

        tup.setBackground(new java.awt.Color(0, 255, 204));
        tup.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tup.setText("Update");
        tup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupActionPerformed(evt);
            }
        });
        getContentPane().add(tup, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 110, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 40));

        trback.setBackground(new java.awt.Color(0, 0, 0));
        trback.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        trback.setForeground(new java.awt.Color(255, 0, 0));
        trback.setText("<<<");
        trback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trbackActionPerformed(evt);
            }
        });
        getContentPane().add(trback, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 447, 90, 30));

        trplab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        trplab.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(trplab, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 400, 40));

        chose.add(mentor);
        mentor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mentor.setForeground(new java.awt.Color(255, 0, 51));
        mentor.setText("MENTOR");
        mentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentorActionPerformed(evt);
            }
        });
        getContentPane().add(mentor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 20));

        chose.add(FRESHER);
        FRESHER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FRESHER.setForeground(new java.awt.Color(255, 0, 0));
        FRESHER.setText("FRESHER");
        FRESHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRESHERActionPerformed(evt);
            }
        });
        getContentPane().add(FRESHER, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbrActionPerformed

    }//GEN-LAST:event_tmbrActionPerformed

    private void tclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tclrActionPerformed
        tmbr.setText("");
        tnidr.setText("");
        chose.clearSelection();
        tcon.setText("");
        tnewpa.setText("");
        tcon.setBackground(Color.WHITE);
    }//GEN-LAST:event_tclrActionPerformed

    private void tverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tverActionPerformed
        String admobile = tmbr.getText();
        String adnid = tnidr.getText();
        dbc = new DBConnect();

        if (admobile.equals("") || adnid.equals("") || count == 0) {
            JOptionPane.showMessageDialog(null, " Empty Password or UserName", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        }
        else{
        if (count == 1) {
            try {

                dbc.connectToDB();

                String sql = "SELECT * FROM MENTOR WHERE NID='" + adnid + "' AND MOBILE='" + admobile + "' ";

                ResultSet rs;
                rs = dbc.queryToDB(sql);

                if (rs.next()) {
                    tcon.setBackground(Color.GREEN);
                    tcon.setText("  !!! Verification Successful !!!");
                    flag = 1;

                } else {

                    tcon.setBackground(Color.RED);
                    tcon.setText(" Sorry  !!! Profile Not Found  !!!");

                }
                dbc.disconnectFromDB();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if (count == 2) {
            try {

                dbc.connectToDB();

                String sql = "SELECT * FROM TRAINEREG WHERE NID='" + adnid + "' AND MOBILE='" + admobile + "' ";

                ResultSet rs;
                rs = dbc.queryToDB(sql);

                if (rs.next()) {
                    tcon.setBackground(Color.GREEN);
                    tcon.setText("  !!! Verification Successful !!!");
                    flag = 1;

                } else {

                    tcon.setBackground(Color.RED);
                    tcon.setText(" Sorry  !!! Profile Not Found  !!!");

                }
                dbc.disconnectFromDB();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        }

    }//GEN-LAST:event_tverActionPerformed

    private void tconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tconActionPerformed

    }//GEN-LAST:event_tconActionPerformed

    private void tnewpaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnewpaMouseEntered
        trplab.setText("*Must be 8 characters (At least 1 Capital Letter & 1 Number)");
    }//GEN-LAST:event_tnewpaMouseEntered

    private void tnewpaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnewpaMouseExited
        trplab.setText("");
    }//GEN-LAST:event_tnewpaMouseExited

    private void tupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupActionPerformed
        if (flag == 1) {
            String tnewp = new String(tnewpa.getPassword());
            String tmobile = tmbr.getText();
            String tnid = tnidr.getText();

            boolean adrpa = checkpass(tnewp);

            if (count == 1) {
                try {
                    if (tnewp.length() == 8 && (adrpa)) {
                        dbc.connectToDB();
                        String sql = " UPDATE MENTOR SET PASS='" + tnewp + "'   WHERE NID='" + tnid + "' AND MOBILE='" + tmobile + "' ";
                        dbc.insertDataToDB(sql);

                        JOptionPane.showMessageDialog(null, " Successfully Update the password", "Hurrah!!", JOptionPane.DEFAULT_OPTION);

                        dbc.disconnectFromDB();
                        dispose();

                        TrainerLog t = new TrainerLog();
                        t.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, " Invalid Password ", "Warning", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            if (count == 2) {
                try {
                    if (tnewp.length() == 8 && (adrpa)) {
                        dbc.connectToDB();
                        String sql = " UPDATE TRAINEREG SET PASS='" + tnewp + "'   WHERE NID='" + tnid + "' AND MOBILE='" + tmobile + "' ";
                        dbc.insertDataToDB(sql);

                        JOptionPane.showMessageDialog(null, " Successfully Update the password", "Hurrah!!", JOptionPane.DEFAULT_OPTION);

                        dbc.disconnectFromDB();

                        TrainerLog t = new TrainerLog();
                        t.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, " Invalid Password ", "Warning", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

        } else {
            tcon.setBackground(Color.YELLOW);
            tcon.setText("Please Verify Yourself");
        }
    }//GEN-LAST:event_tupActionPerformed

    private void trbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trbackActionPerformed
        TrainerLog t = new TrainerLog();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_trbackActionPerformed

    private void mentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentorActionPerformed
        JOptionPane.showMessageDialog(null, "  Select as a Mentor ", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        count = 1;
    }//GEN-LAST:event_mentorActionPerformed

    private void FRESHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRESHERActionPerformed
        JOptionPane.showMessageDialog(null, "  Select as a Fresher ", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        count = 2;
    }//GEN-LAST:event_FRESHERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainer_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainer_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainer_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainer_Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainer_Reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FRESHER;
    private javax.swing.ButtonGroup chose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton mentor;
    private javax.swing.JButton tclr;
    private javax.swing.JTextField tcon;
    private javax.swing.JTextField tmbr;
    private javax.swing.JPasswordField tnewpa;
    private javax.swing.JTextField tnidr;
    private javax.swing.JButton trback;
    private javax.swing.JLabel trplab;
    private javax.swing.JButton tup;
    private javax.swing.JButton tver;
    // End of variables declaration//GEN-END:variables
}
