/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hocce Na
 */
public class TrainerLog extends javax.swing.JFrame {

    /**
     * Creates new form TrainerLog
     */
    public TrainerLog() {
        initComponents();
    }
    int flag = 0;
    DBConnect dbc;
    //DBConnect dbc2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        res = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        trainer_logbutton = new javax.swing.JButton();
        tpass = new javax.swing.JPasswordField();
        tmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mentor = new javax.swing.JRadioButton();
        fresher = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 100, 700, 500));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email      :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 132, 166, 37));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 187, 176, 33));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("<<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 40));

        res.setBackground(new java.awt.Color(255, 204, 204));
        res.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        res.setText("Reset");
        res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resMouseExited(evt);
            }
        });
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Forgotten password?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        trainer_logbutton.setBackground(new java.awt.Color(204, 255, 204));
        trainer_logbutton.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        trainer_logbutton.setText("Login");
        trainer_logbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trainer_logbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trainer_logbuttonMouseExited(evt);
            }
        });
        trainer_logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainer_logbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(trainer_logbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 206, 45));

        tpass.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 187, 220, 33));

        tmail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(tmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 131, 220, 38));

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trainer Log");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 301, 63));

        type.add(mentor);
        mentor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mentor.setForeground(new java.awt.Color(255, 255, 255));
        mentor.setText("MENTOR");
        mentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentorActionPerformed(evt);
            }
        });
        getContentPane().add(mentor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        type.add(fresher);
        fresher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fresher.setForeground(new java.awt.Color(255, 255, 255));
        fresher.setText("FRESHER");
        fresher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresherActionPerformed(evt);
            }
        });
        getContentPane().add(fresher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Pic/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setForeground(Color.WHITE);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setForeground(Color.red);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void resMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resMouseEntered
        res.setBackground(Color.red);
    }//GEN-LAST:event_resMouseEntered

    private void resMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resMouseExited
        res.setBackground(new Color(255, 128, 128));
    }//GEN-LAST:event_resMouseExited

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        Trainer_Reset tdr = new Trainer_Reset();
        tdr.setVisible(true);
        dispose();
    }//GEN-LAST:event_resActionPerformed

    private void trainer_logbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainer_logbuttonMouseEntered
        trainer_logbutton.setBackground(Color.GREEN);
    }//GEN-LAST:event_trainer_logbuttonMouseEntered

    private void trainer_logbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainer_logbuttonMouseExited
        trainer_logbutton.setBackground(new Color(179, 255, 179));
    }//GEN-LAST:event_trainer_logbuttonMouseExited

    private void trainer_logbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainer_logbuttonActionPerformed
        Fresher_Info fi = new Fresher_Info();
        Mentor_Info mi = new Mentor_Info();
           dbc = new DBConnect();
        String t_mail = tmail.getText();
        String tpa = new String(tpass.getPassword());

        if (t_mail.equals("") || tpa.equals("") || flag == 0) {
            JOptionPane.showMessageDialog(null, " Empty Field", "Warning !!!", JOptionPane.ERROR_MESSAGE);
        }

        if (flag == 1 || flag == 2) {
          try{
                dbc.connectToDB();
                
            if (flag == 1) {
                try {
                 
                  
                    String sql1 = "SELECT * FROM MENTOR WHERE EMAIL='" + t_mail + "' AND PASS='" + tpa + "'";

                    ResultSet rs1;
                    rs1 = dbc.queryToDB(sql1);
                    if (rs1.next()) {

                        mi.setOwn_id(Integer.parseInt(rs1.getString(1)));

                        mi.setFname(rs1.getString(2));
                        mi.setAg(Integer.parseInt(rs1.getString(3)));
                        mi.setGen(rs1.getString(4));
                        mi.setHt(rs1.getString(5));
                        mi.setWt(rs1.getString(6));
                        mi.setBl(rs1.getString(7));
                        mi.setMob(rs1.getString(8));
                        mi.setMail(rs1.getString(9));
                        mi.setNd(rs1.getString(10));
                        mi.setPa(rs1.getString(11));
                        mi.setPic(rs1.getString(12));

                        mi.setTime(rs1.getString(13));
                        mi.setPack(rs1.getString(14));
                        mi.setDate(rs1.getString(15));
                        mi.setSalary(Integer.parseInt(rs1.getString(16)));
                        
                        dispose();
                         TrainerMain tm = new TrainerMain(fi, mi, flag);
                         tm.setVisible(true);
                        

                    }else{
                    JOptionPane.showMessageDialog(null, " Invalid Password or Email", "Warning", JOptionPane.ERROR_MESSAGE);
                    tmail.setText("");
                    tpass.setText("");
                }
                } catch (Exception e) {
                 //   JOptionPane.showMessageDialog(null, e,"Warning !!!",JOptionPane.ERROR_MESSAGE);
                   Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, e);
                }

            }

            if (flag == 2) {
                try {
                    
                    
                    String sql = "SELECT * FROM TRAINEREG WHERE EMAIL='" + t_mail + "' AND PASS='" + tpa + "'";

                    ResultSet rs;
                    rs = dbc.queryToDB(sql);
                    if (rs.next()) {

                        fi.setOwn_id(Integer.parseInt(rs.getString(1)));

                        fi.setFname(rs.getString(2));
                        fi.setAg(Integer.parseInt(rs.getString(3)));
                        fi.setGen(rs.getString(4));
                        fi.setHt(rs.getString(5));
                        fi.setWt(rs.getString(6));
                        fi.setBl(rs.getString(7));
                        fi.setMob(rs.getString(8));
                        fi.setMail(rs.getString(9));
                        fi.setNd(rs.getString(10));
                        fi.setPa(rs.getString(11));
                        fi.setPic(rs.getString(12));

                        fi.setMt_name(rs.getString(13));
                        fi.setMt_id(Integer.parseInt(rs.getString(14)));
                        fi.setTime(rs.getString(15));
                        fi.setPack(rs.getString(16));
                        fi.setMtime(rs.getString(17));
                        fi.setJdate(rs.getString(18));
                       fi.setSalary(Integer.parseInt(rs.getString(19)));

                        
                        dispose();
                         TrainerMain tm = new TrainerMain(fi, mi, flag);
                         tm.setVisible(true);

                    }else{
                    JOptionPane.showMessageDialog(null, " Invalid Password or Email", "Warning", JOptionPane.ERROR_MESSAGE);
                    tmail.setText("");
                    tpass.setText("");
                }
                } catch (Exception e) {
                          JOptionPane.showMessageDialog(null, e,"Caution !!!",JOptionPane.ERROR_MESSAGE);
                }
            }
            
            
             } catch (Exception e) {
                          JOptionPane.showMessageDialog(null, e,"Caution !!!",JOptionPane.ERROR_MESSAGE);
                }
            
        } 
        dbc.disconnectFromDB();
//        dbc2.disconnectFromDB();
 

    }//GEN-LAST:event_trainer_logbuttonActionPerformed

    private void mentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentorActionPerformed
        JOptionPane.showMessageDialog(null, "  Login as a Mentor ", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        flag = 1;
    }//GEN-LAST:event_mentorActionPerformed

    private void fresherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresherActionPerformed
        JOptionPane.showMessageDialog(null, "  Login as a Fresher ", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        flag = 2;
    }//GEN-LAST:event_fresherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JRadioButton fresher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton mentor;
    private javax.swing.JButton res;
    private javax.swing.JTextField tmail;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JButton trainer_logbutton;
    private javax.swing.ButtonGroup type;
    // End of variables declaration//GEN-END:variables
}
